In [2]:
import pandas as pd
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)

from src.preprocessing import process_raw_recipes_pipeline

In [5]:
input_raw_recipes_path = "../data/raw/RAW_recipes.csv"

print(f"Démarrage du prétraitement de : {input_raw_recipes_path}")
df_processed_recipes = process_raw_recipes_pipeline(input_raw_recipes_path)
print("Prétraitement terminé.")

Démarrage du prétraitement de : ../data/raw/RAW_recipes.csv
Prétraitement terminé.

In [6]:
print("\nPremières lignes du DataFrame après prétraitement :")
display(df_processed_recipes.head())

Premières lignes du DataFrame après prétraitement :

,name,id,minutes,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,ingredients_text,steps_text,document
0,arriba baked winter squash mexican style,137739,55,"[60-minutes-or-less, time-to-make, course, mai...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"[make a choice and proceed with recipe, depend...",autumn is my favorite time of year to cook! th...,"[winter squash, mexican seasoning, mixed spice...",7,winter squash\nmexican seasoning\nmixed spice\...,1. make a choice and proceed with recipe\n2. d...,\n Title: arriba baked winter squash mexi...
1,a bit different breakfast pizza,31490,30,"[30-minutes-or-less, time-to-make, course, mai...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"[preheat oven to 425 degrees f, press dough in...",this recipe calls for the crust to be prebaked...,"[prepared pizza crust, sausage patty, eggs, mi...",6,prepared pizza crust\nsausage patty\neggs\nmil...,1. preheat oven to 425 degrees f\n2. press dou...,\n Title: a bit different breakfast pizza\...
2,all in the kitchen chili,112140,130,"[time-to-make, course, preparation, main-dish,...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"[brown ground beef in large pot, add chopped o...",this modified version of 'mom's' chili was a h...,"[ground beef, yellow onions, diced tomatoes, t...",13,ground beef\nyellow onions\ndiced tomatoes\nto...,1. brown ground beef in large pot\n2. add chop...,\n Title: all in the kitchen chili\n Ta...
3,alouette potatoes,59389,45,"[60-minutes-or-less, time-to-make, course, mai...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,[place potatoes in a large pot of lightly salt...,"this is a super easy, great tasting, make ahea...","[spreadable cheese with garlic and herbs, new ...",11,spreadable cheese with garlic and herbs\nnew p...,1. place potatoes in a large pot of lightly sa...,\n Title: alouette potatoes\n Tags: 60-...
4,amish tomato ketchup for canning,44061,190,"[weeknight, time-to-make, course, main-ingredi...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,"[mix all ingredients& boil for 2 1 / 2 hours ,...",my dh's amish mother raised him on this recipe...,"[tomato juice, apple cider vinegar, sugar, sal...",8,tomato juice\napple cider vinegar\nsugar\nsalt...,1. mix all ingredients& boil for 2 1 / 2 hours...,\n Title: amish tomato ketchup for cannin...

In [7]:
output_processed_path = "../data/processed/raw_recipes_processed.csv"
# Sauvegarde en CSV, sans l'index du DataFrame
df_processed_recipes.to_csv(output_processed_path, index=False)
print(f"\nDataset traité sauvegardé dans : {output_processed_path}")

Dataset traité sauvegardé dans : ../data/processed/raw_recipes_processed.csv

In [1]:
import pandas as pd
import sys
import os

# --- Début de la correction pour le chemin d'importation des modules 'src' ---
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.append(project_root)
# --- Fin de la correction ---

# Importer les fonctions de notre module de prétraitement (on importe load_and_process_moroccan_recipes)
from src.preprocessing import process_raw_recipes_pipeline, load_and_process_moroccan_recipes, build_recipe_document

In [2]:
input_raw_recipes_path = "../data/raw/RAW_recipes.csv"

# Exécuter le pipeline de prétraitement pour le dataset RAW_recipes
print(f"Démarrage du prétraitement de : {input_raw_recipes_path}")
df_processed_recipes = process_raw_recipes_pipeline(input_raw_recipes_path)
print("Prétraitement terminé pour RAW_recipes.")

Démarrage du prétraitement de : ../data/raw/RAW_recipes.csv
Prétraitement terminé pour RAW_recipes.

In [4]:
input_moroccan_recipes_path = "../data/raw/moroccan_recipes_dataset.csv"
# Le nom de la colonne contenant la recette complète est 'prompt'
moroccan_recipe_text_column_name = "prompt"

print(f"Démarrage du prétraitement de : {input_moroccan_recipes_path}")
# Utiliser la nouvelle fonction pour charger et traiter les recettes marocaines
df_processed_moroccan_recipes = load_and_process_moroccan_recipes(
    input_moroccan_recipes_path,
    recipe_text_column=moroccan_recipe_text_column_name
)

# Appliquer la fonction build_recipe_document pour créer la colonne 'document'
# La fonction load_and_process_moroccan_recipes prépare déjà ingredients_text et steps_text
df_processed_moroccan_recipes["document"] = df_processed_moroccan_recipes.apply(build_recipe_document, axis=1)

print("Prétraitement terminé pour les recettes marocaines.")

Démarrage du prétraitement de : ../data/raw/moroccan_recipes_dataset.csv
Prétraitement terminé pour les recettes marocaines.

In [5]:
print("\nPremières lignes du DataFrame des recettes marocaines après prétraitement :")
display(df_processed_moroccan_recipes.head())

Premières lignes du DataFrame des recettes marocaines après prétraitement :

,name,ingredients,steps,tags,ingredients_text,steps_text,document
0,Duck and prune tagine,"[2 tbsp olive oil, 2 cinnamon sticks, 3 red on...",[Pour the oil into a heavy-based pan or casser...,"[marocaine, north african]",2 tbsp olive oil\n2 cinnamon sticks\n3 red oni...,1. Pour the oil into a heavy-based pan or cass...,\n Title: Duck and prune tagine\n Tags: ...
1,Potato tagine with baked halloumi,"[2 tbsp vegetable oil, 2 onions, sliced, 6 gar...",[Heat the oven to 180°C fan/gas 6. Heat the oi...,"[marocaine, north african]","2 tbsp vegetable oil\n2 onions, sliced\n6 garl...",1. Heat the oven to 180°C fan/gas 6. Heat the ...,\n Title: Potato tagine with baked halloumi...
2,Merguez sausages with crispy chickpeas and pre...,"[2 x 400g tins chickpeas, drained, 3 tbsp oliv...",[Heat the oven to 180°C fan/gas 6. Put the chi...,"[marocaine, north african]","2 x 400g tins chickpeas, drained\n3 tbsp olive...",1. Heat the oven to 180°C fan/gas 6. Put the c...,\n Title: Merguez sausages with crispy chic...
3,Chicken tagine casserole,"[8 small free-range chicken thighs, 2 medium r...",[Heat the oven to 180ºC fan/gas 6. Slash the s...,"[marocaine, north african]",8 small free-range chicken thighs\n2 medium re...,1. Heat the oven to 180ºC fan/gas 6. Slash the...,\n Title: Chicken tagine casserole\n Tag...
4,Preserved lemons,[12 small unwaxed lemons (about 1kg; see tips)...,[Juice 4 of the lemons and set the juice aside...,"[marocaine, north african]",12 small unwaxed lemons (about 1kg; see tips)\...,1. Juice 4 of the lemons and set the juice asi...,\n Title: Preserved lemons\n Tags: maroc...

In [6]:
# Afficher un exemple de la colonne 'document' pour les recettes marocaines
print("\nExemple de la colonne 'document' (première recette marocaine) :")
print(df_processed_moroccan_recipes['document'].iloc[0])

Exemple de la colonne 'document' (première recette marocaine) :

    Title: Duck and prune tagine
    Tags: marocaine, north african
    Ingredients:
    2 tbsp olive oil
2 cinnamon sticks
3 red onions, finely sliced
5 garlic cloves, finely sliced
2 tbsp harissa
4 tbsp ras el hanout
2 tsp ground ginger
4 large duck legs
1 litre chicken stock
2 x 400g tins chopped tomatoes
2 preserved lemons
400g tin chickpeas, drained
150g pitted kalamata olives
200g soft pitted prunes

    Instructions:
    1. Pour the oil into a heavy-based pan or casserole over a medium heat, then add the cinnamon sticks followed by the onions, garlic and a pinch of salt. Cook for about 5 minutes until the onions are just starting to soften, then add the harissa, ras el hanout and ground ginger. Stir for another minute.#
2. Add the duck legs, then cover with the stock and tinned tomatoes. Quarter the preserved lemons and scrape out the flesh, reserving half of it, then finely chop the peel and add the reserved flesh and peel to the pan. Leave to cook over a low heat, uncovered, for 2 hours.
3. Carefully remove the duck legs from the pan and use a fork to pull the meat from the bones – it should come away easily. Discard the bones and skin, then return the meat to the pan. Add the chickpeas, olives and prunes and cook for a further 1 hour.
4. Serve the tagine sprinkled with the chopped herbs, flaked almonds and pomegranate seeds, with rice on the side.

In [7]:
# Concaténer les deux DataFrames traités
df_combined_recipes = pd.concat(
    [df_processed_recipes, df_processed_moroccan_recipes],
    ignore_index=True # Pour réinitialiser l'index après la concaténation
)

print(f"\nFusion des datasets terminée. Nombre total de recettes : {len(df_combined_recipes)}")
print("Informations sur le DataFrame combiné :")
df_combined_recipes.info()

Fusion des datasets terminée. Nombre total de recettes : 236263
Informations sur le DataFrame combiné :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236263 entries, 0 to 236262
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   name              236263 non-null  object
 1   id                231636 non-null  float64
 2   minutes           231636 non-null  float64
 3   tags              236263 non-null  object
 4   nutrition         231636 non-null  object
 5   n_steps           231636 non-null  float64
 6   steps             236263 non-null  object
 7   description       226657 non-null  object
 8   ingredients       236263 non-null  object
 9   n_ingredients     231636 non-null  float64
 10  ingredients_text  236263 non-null  object
 11  steps_text        236263 non-null  object
 12  document          236263 non-null  object
dtypes: float64(4), object(9)
memory usage: 23.4+ MB

In [8]:
print("\nAperçu du DataFrame combiné :")
display(df_combined_recipes.head())
display(df_combined_recipes.tail())

Aperçu du DataFrame combiné :

,name,id,minutes,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,ingredients_text,steps_text,document
0,arriba baked winter squash mexican style,137739.0,55.0,"[60-minutes-or-less, time-to-make, course, mai...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11.0,"[make a choice and proceed with recipe, depend...",autumn is my favorite time of year to cook! th...,"[winter squash, mexican seasoning, mixed spice...",7.0,winter squash\nmexican seasoning\nmixed spice\...,1. make a choice and proceed with recipe\n2. d...,\n Title: arriba baked winter squash mexi...
1,a bit different breakfast pizza,31490.0,30.0,"[30-minutes-or-less, time-to-make, course, mai...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9.0,"[preheat oven to 425 degrees f, press dough in...",this recipe calls for the crust to be prebaked...,"[prepared pizza crust, sausage patty, eggs, mi...",6.0,prepared pizza crust\nsausage patty\neggs\nmil...,1. preheat oven to 425 degrees f\n2. press dou...,\n Title: a bit different breakfast pizza\...
2,all in the kitchen chili,112140.0,130.0,"[time-to-make, course, preparation, main-dish,...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6.0,"[brown ground beef in large pot, add chopped o...",this modified version of 'mom's' chili was a h...,"[ground beef, yellow onions, diced tomatoes, t...",13.0,ground beef\nyellow onions\ndiced tomatoes\nto...,1. brown ground beef in large pot\n2. add chop...,\n Title: all in the kitchen chili\n Ta...
3,alouette potatoes,59389.0,45.0,"[60-minutes-or-less, time-to-make, course, mai...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11.0,[place potatoes in a large pot of lightly salt...,"this is a super easy, great tasting, make ahea...","[spreadable cheese with garlic and herbs, new ...",11.0,spreadable cheese with garlic and herbs\nnew p...,1. place potatoes in a large pot of lightly sa...,\n Title: alouette potatoes\n Tags: 60-...
4,amish tomato ketchup for canning,44061.0,190.0,"[weeknight, time-to-make, course, main-ingredi...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5.0,"[mix all ingredients& boil for 2 1 / 2 hours ,...",my dh's amish mother raised him on this recipe...,"[tomato juice, apple cider vinegar, sugar, sal...",8.0,tomato juice\napple cider vinegar\nsugar\nsalt...,1. mix all ingredients& boil for 2 1 / 2 hours...,\n Title: amish tomato ketchup for cannin...

,name,id,minutes,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,ingredients_text,steps_text,document
236258,Nom de recette inconnu,NaN,NaN,"[marocaine, north african]",NaN,NaN,[],NaN,[],NaN,,,\n Title: Nom de recette inconnu\n Tags:...
236259,Nom de recette inconnu,NaN,NaN,"[marocaine, north african]",NaN,NaN,[],NaN,[],NaN,,,\n Title: Nom de recette inconnu\n Tags:...
236260,Nom de recette inconnu,NaN,NaN,"[marocaine, north african]",NaN,NaN,[],NaN,[],NaN,,,\n Title: Nom de recette inconnu\n Tags:...
236261,Nom de recette inconnu,NaN,NaN,"[marocaine, north african]",NaN,NaN,[],NaN,[],NaN,,,\n Title: Nom de recette inconnu\n Tags:...
236262,Nom de recette inconnu,NaN,NaN,"[marocaine, north african]",NaN,NaN,[],NaN,[],NaN,,,\n Title: Nom de recette inconnu\n Tags:...

In [27]:
output_combined_path = "../data/processed/all_recipes_combined_processed.csv"
df_combined_recipes.to_csv(output_combined_path, index=False)
print(f"\nDataset combiné sauvegardé dans : {output_combined_path}")

Dataset combiné sauvegardé dans : ../data/processed/all_recipes_combined_processed.csv

In [1]:
import pandas as pd
import os
import re # Nécessaire pour les fonctions de nettoyage de texte si elles sont appelées
from IPython.display import display # Pour afficher les DataFrames dans un notebook

# --- Définition explicite du dossier de sortie ---
output_dir = '../data/processed'
os.makedirs(output_dir, exist_ok=True) # S'assurer que le dossier existe
# -------------------------------------------------

print(f"Dossier de sortie défini : {output_dir}")
print("\nDébut du nettoyage avancé et de la déduplication du fichier existant (préservant la colonne 'document')...")

Dossier de sortie défini : ../data/processed

Début du nettoyage avancé et de la déduplication du fichier existant (préservant la colonne 'document')...

In [2]:
input_file_path = os.path.join(output_dir, 'all_recipes_combined_processed.csv')
try:
    # Charger avec toutes les colonnes par défaut, y compris 'document'
    df_recipes = pd.read_csv(input_file_path)
    print(f"Fichier '{input_file_path}' chargé avec succès. Taille initiale : {len(df_recipes)} recettes.")
except FileNotFoundError:
    print(f"Erreur : Le fichier '{input_file_path}' n'a pas été trouvé.")
    print("Assure-toi que tu as exécuté les étapes précédentes pour créer ce fichier.")
    exit() # Quitte si le fichier n'est pas trouvé

Fichier '../data/processed\all_recipes_combined_processed.csv' chargé avec succès. Taille initiale : 236263 recettes.

In [3]:
print("\nApplication du nettoyage des noms et de la déduplication...")
print("\nRemplacement des NaN par des chaînes vides ('') dans 'ingredients_text' et 'steps_text'...")

df_recipes['ingredients_text'].fillna('', inplace=True)
df_recipes['steps_text'].fillna('', inplace=True)

print("Remplacement terminé. Les colonnes devraient maintenant être propres.")

# Vérification (optionnel, pour s'assurer qu'il n'y a plus de NaN)
print("\nVérification des valeurs NaN après remplacement :")
print(df_recipes[['ingredients_text', 'steps_text']].isna().sum())
# 2.1 Supprimer les recettes avec le nom exact "Nom de recette inconnu"
initial_rows = len(df_recipes)
df_filtered_by_name = df_recipes[df_recipes['name'] != 'Nom de recette inconnu'].copy()

print(f"Recettes après suppression des noms 'Nom de recette inconnu' : {len(df_filtered_by_name)} (supprimées: {initial_rows - len(df_filtered_by_name)})")

Application du nettoyage des noms et de la déduplication...

Remplacement des NaN par des chaînes vides ('') dans 'ingredients_text' et 'steps_text'...
Remplacement terminé. Les colonnes devraient maintenant être propres.

Vérification des valeurs NaN après remplacement :
ingredients_text    0
steps_text          0
dtype: int64

C:\Users\mohme\AppData\Local\Temp\ipykernel_15592\3158378768.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_recipes['ingredients_text'].fillna('', inplace=True)
C:\Users\mohme\AppData\Local\Temp\ipykernel_15592\3158378768.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_recipes['steps_text'].fillna('', inplace=True)

Recettes après suppression des noms 'Nom de recette inconnu' : 236219 (supprimées: 44)

In [4]:
print("\nRemplacement des NaN par des chaînes vides ('') dans 'ingredients_text' et 'steps_text'...")

df_recipes['ingredients_text'].fillna('', inplace=True)
df_recipes['steps_text'].fillna('', inplace=True)

print("Remplacement terminé. Les colonnes devraient maintenant être propres.")

# Vérification (optionnel, pour s'assurer qu'il n'y a plus de NaN)
print("\nVérification des valeurs NaN après remplacement :")
print(df_recipes[['ingredients_text', 'steps_text']].isna().sum())

Remplacement des NaN par des chaînes vides ('') dans 'ingredients_text' et 'steps_text'...
Remplacement terminé. Les colonnes devraient maintenant être propres.

Vérification des valeurs NaN après remplacement :
ingredients_text    0
steps_text          0
dtype: int64

In [5]:
# 2.2 Identifier et garder les doublons avec le plus d'informations
# Créer une colonne pour évaluer la quantité d'informations
# Les colonnes sont maintenant garanties d'être des chaînes
df_filtered_by_name['info_length'] = df_filtered_by_name.apply(
    lambda row: len(row['ingredients_text']) + len(row['steps_text']), # safe_str() n'est plus strictement nécessaire ici car fillna a été fait avant
    axis=1
)

# Trier par nom, puis par longueur d'information décroissante
# Garder la première occurrence (celle avec le plus d'infos) pour chaque nom
df_cleaned_recipes = df_filtered_by_name.sort_values(
    by=['name', 'info_length'],
    ascending=[True, False]
).drop_duplicates(subset=['name'], keep='first')

# Supprimer la colonne temporaire 'info_length'
df_cleaned_recipes = df_cleaned_recipes.drop(columns=['info_length'])

print(f"Recettes après déduplication (gardant la plus complète) : {len(df_cleaned_recipes)} (doublons supprimés: {len(df_filtered_by_name) - len(df_cleaned_recipes)})")
print("Aperçu du DataFrame nettoyé et dédupliqué (avec colonne 'document' préservée) :")
display(df_cleaned_recipes.head())

Recettes après déduplication (gardant la plus complète) : 232658 (doublons supprimés: 3561)
Aperçu du DataFrame nettoyé et dédupliqué (avec colonne 'document' préservée) :

,name,id,minutes,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,ingredients_text,steps_text,document
235120,"""It'S Maaaaa-Gic!"" Moroccan Carrots",NaN,NaN,"['marocaine', 'north african']",NaN,NaN,['Cook the carrots in a small amount of salted...,NaN,"['1 pound skinny carrots, scraped and cut into...",NaN,"1 pound skinny carrots, scraped and cut into l...",1. Cook the carrots in a small amount of salte...,"\n Title: ""It'S Maaaaa-Gic!"" Moroccan Carro..."
235159,"""Moroccan Guacamole"" Toasts With Fried Egg",NaN,NaN,"['marocaine', 'north african']",NaN,NaN,"['Make ""guacamole:"" Squeeze or scoop avocado f...",NaN,"['1 ripe avocado, halved and pitted', '1/8 to ...",NaN,"1 ripe avocado, halved and pitted\n1/8 to 1/4 ...","1. Make ""guacamole:"" Squeeze or scoop avocado ...","\n Title: ""Moroccan Guacamole"" Toasts With ..."
729,0 carb 0 cal gummy worms,283618.0,45.0,"['60-minutes-or-less', 'time-to-make', 'course...","[384.7, 0.0, 0.0, 70.0, 159.0, 0.0, 6.0]",15.0,"['stir all ingredients until dissolved', 'pour...",these are delicious and guilt free!\r\n\r\n*if...,"['sugar-free jello', 'gelatin', 'boiling water']",3.0,sugar-free jello\ngelatin\nboiling water,1. stir all ingredients until dissolved\n2. po...,\n Title: 0 carb 0 cal gummy worms\n T...
733,0 fat chunky watermelon salsa,176996.0,45.0,"['60-minutes-or-less', 'time-to-make', 'course...","[57.7, 0.0, 39.0, 0.0, 2.0, 0.0, 4.0]",6.0,['using a small sharp knife cut peel and white...,this is fantastic served with grilled seafood ...,"['lime', 'watermelon', 'cucumber', 'green onio...",8.0,lime\nwatermelon\ncucumber\ngreen onion\ncilan...,1. using a small sharp knife cut peel and whit...,\n Title: 0 fat chunky watermelon salsa\n ...
730,0 point ice cream only 1 ingredient,480558.0,125.0,"['time-to-make', 'course', 'main-ingredient', ...","[304.1, 13.0, 121.0, 3.0, 13.0, 9.0, 19.0]",5.0,"['1) peel your bananas first', '2) cut them in...",yummy!! (got this recipe from \r\nhttp://www.t...,"['bananas', 'peanut butter', 'honey']",3.0,bananas\npeanut butter\nhoney,1. 1) peel your bananas first\n2. 2) cut them ...,\n Title: 0 point ice cream only 1 ingredi...

In [6]:
# 3. Sauvegarde du Dataset Nettoyé
output_file_path_cleaned = os.path.join(output_dir, 'all_recipes_combined_processed2.csv')
df_cleaned_recipes.to_csv(output_file_path_cleaned, index=False)

print(f"\nDataset nettoyé et dédupliqué sauvegardé sous : {output_file_path_cleaned}")
print(f"Taille finale du dataset : {len(df_cleaned_recipes)} recettes.")

Dataset nettoyé et dédupliqué sauvegardé sous : ../data/processed\all_recipes_combined_processed2.csv
Taille finale du dataset : 232658 recettes.

In [1]:
import pandas as pd
import os

# --- Définition explicite du dossier de sortie ---
output_dir = '../data/processed'
os.makedirs(output_dir, exist_ok=True)
# -------------------------------------------------

print(f"Dossier de sortie défini : {output_dir}")
print("\nDébut du nettoyage final : suppression des lignes sans ingrédients_text ou steps_text...")

# Nom du fichier à nettoyer (ton fichier déjà traité)
input_file_to_clean = os.path.join(output_dir, 'all_recipes_combined_processed2.csv')

try:
    df_final_clean = pd.read_csv(input_file_to_clean)
    print(f"Fichier '{input_file_to_clean}' chargé avec succès. Taille initiale : {len(df_final_clean)} recettes.")
except FileNotFoundError:
    print(f"Erreur : Le fichier '{input_file_to_clean}' n'a pas été trouvé.")
    print("Assure-toi que tu as le bon chemin et nom de fichier.")
    exit()

# --- Nettoyage des colonnes : S'assurer qu'elles sont des chaînes et gérer les NaN/vides ---
# 1. Remplacer tous les NaN par des chaînes vides pour faciliter la vérification de longueur
df_final_clean['ingredients_text'] = df_final_clean['ingredients_text'].fillna('')
df_final_clean['steps_text'] = df_final_clean['steps_text'].fillna('')

# 2. Convertir explicitement en type chaîne pour toute la colonne, au cas où il y aurait d'autres types inattendus
df_final_clean['ingredients_text'] = df_final_clean['ingredients_text'].astype(str)
df_final_clean['steps_text'] = df_final_clean['steps_text'].astype(str)

print("\nColonnes 'ingredients_text' et 'steps_text' préparées (NaN remplacés par '').")


# --- Filtrage : Supprimer les lignes où ingredients_text OU steps_text est vide ---
initial_rows = len(df_final_clean)

# Condition: filtrer les lignes où la longueur de ingredients_text est 0 OU la longueur de steps_text est 0
# Nous nous basons sur la longueur après s'être assurés qu'elles sont des chaînes.
df_final_clean = df_final_clean[
    (df_final_clean['ingredients_text'].str.strip() != '') &
    (df_final_clean['steps_text'].str.strip() != '')
].copy() # .copy() pour éviter les avertissements

print(f"\nRecettes après suppression des lignes sans ingrédients ou étapes : {len(df_final_clean)} (supprimées: {initial_rows - len(df_final_clean)})")
print("Aperçu du DataFrame après le nettoyage final :")
display(df_final_clean.head())

Dossier de sortie défini : ../data/processed

Début du nettoyage final : suppression des lignes sans ingrédients_text ou steps_text...
Fichier '../data/processed\all_recipes_combined_processed2.csv' chargé avec succès. Taille initiale : 232658 recettes.

Colonnes 'ingredients_text' et 'steps_text' préparées (NaN remplacés par '').

Recettes après suppression des lignes sans ingrédients ou étapes : 232111 (supprimées: 547)
Aperçu du DataFrame après le nettoyage final :

,name,id,minutes,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,ingredients_text,steps_text,document
0,"""It'S Maaaaa-Gic!"" Moroccan Carrots",NaN,NaN,"['marocaine', 'north african']",NaN,NaN,['Cook the carrots in a small amount of salted...,NaN,"['1 pound skinny carrots, scraped and cut into...",NaN,"1 pound skinny carrots, scraped and cut into l...",1. Cook the carrots in a small amount of salte...,"\n Title: ""It'S Maaaaa-Gic!"" Moroccan Carro..."
1,"""Moroccan Guacamole"" Toasts With Fried Egg",NaN,NaN,"['marocaine', 'north african']",NaN,NaN,"['Make ""guacamole:"" Squeeze or scoop avocado f...",NaN,"['1 ripe avocado, halved and pitted', '1/8 to ...",NaN,"1 ripe avocado, halved and pitted\n1/8 to 1/4 ...","1. Make ""guacamole:"" Squeeze or scoop avocado ...","\n Title: ""Moroccan Guacamole"" Toasts With ..."
2,0 carb 0 cal gummy worms,283618.0,45.0,"['60-minutes-or-less', 'time-to-make', 'course...","[384.7, 0.0, 0.0, 70.0, 159.0, 0.0, 6.0]",15.0,"['stir all ingredients until dissolved', 'pour...",these are delicious and guilt free!\r\n\r\n*if...,"['sugar-free jello', 'gelatin', 'boiling water']",3.0,sugar-free jello\ngelatin\nboiling water,1. stir all ingredients until dissolved\n2. po...,\n Title: 0 carb 0 cal gummy worms\n T...
3,0 fat chunky watermelon salsa,176996.0,45.0,"['60-minutes-or-less', 'time-to-make', 'course...","[57.7, 0.0, 39.0, 0.0, 2.0, 0.0, 4.0]",6.0,['using a small sharp knife cut peel and white...,this is fantastic served with grilled seafood ...,"['lime', 'watermelon', 'cucumber', 'green onio...",8.0,lime\nwatermelon\ncucumber\ngreen onion\ncilan...,1. using a small sharp knife cut peel and whit...,\n Title: 0 fat chunky watermelon salsa\n ...
4,0 point ice cream only 1 ingredient,480558.0,125.0,"['time-to-make', 'course', 'main-ingredient', ...","[304.1, 13.0, 121.0, 3.0, 13.0, 9.0, 19.0]",5.0,"['1) peel your bananas first', '2) cut them in...",yummy!! (got this recipe from \r\nhttp://www.t...,"['bananas', 'peanut butter', 'honey']",3.0,bananas\npeanut butter\nhoney,1. 1) peel your bananas first\n2. 2) cut them ...,\n Title: 0 point ice cream only 1 ingredi...

In [2]:
# --- Sauvegarde du Dataset Nettoyé Final ---
output_final_cleaned_path = os.path.join(output_dir, 'all_recipes_combined_processed3.csv')
df_final_clean.to_csv(output_final_cleaned_path, index=False)

print(f"\nDataset nettoyé final sauvegardé sous : {output_final_cleaned_path}")
print(f"Taille finale du dataset : {len(df_final_clean)} recettes.")

Dataset nettoyé final sauvegardé sous : ../data/processed\all_recipes_combined_processed3.csv
Taille finale du dataset : 232111 recettes.